version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"

  pre_build:
    commands:
      - echo "Preparing build"

  build:
    commands:
      - echo "Build started"
      - docker build -t brain-tasks-app .

  post_build:
    commands:
      - echo "Build completed"
