version: 0.2

phases:
  pre_build:
    commands:
      - aws eks update-kubeconfig --region ap-south-1 --name brain-cluster

  build:
    commands:
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml

artifacts:
  files:
    - '**/*'
