version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"

  pre_build:
    commands:
      - echo "Updating kubeconfig"
      - aws eks update-kubeconfig --region ap-south-1 --name brain-cluster

  build:
    commands:
      - echo "Deploying application"
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml

  post_build:
    commands:
      - echo "Deployment completed"
